name: Test Secure Action

on:
  workflow_dispatch:
    inputs:
      input_directory:
        description: 'Directory containing API source code (relative to workspace)'
        type: string        

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # - name: Verify input directory
    #   run: |
    #     if [ ! -d "${{ inputs.input_directory }}" ]; then
    #       echo "Input directory not found: ${{ inputs.input_directory }}"
    #       exit 1
    #     fi
    #     echo "Using source code from: ${{ inputs.input_directory }}"
    #     ls -la ${{ inputs.input_directory }}
        
    # - name: Run codeglide
    #   uses: madhavi-opsera/aicodegen@v23
    #   with:
    #     input_directory: ${{ inputs.input_directory }}
    - name: CodeGlide MCP Generator
      uses: CodeGlide/codeglide-mcpgen@v1.0.5
      with:
        input_directory: ${{ inputs.input_directory }}
        create_pr: ${{ inputs.create_pr }}
        create_branch_and_commit: ${{ inputs.create_branch_and_commit }}
        
