name: Test Secure Action

on:
  workflow_dispatch:
    inputs:
      input_directory:
        description: 'Directory containing API source code (relative to workspace)'
        type: string        

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # - name: Verify input directory
    #   run: |
    #     if [ ! -d "${{ inputs.input_directory }}" ]; then
    #       echo "Input directory not found: ${{ inputs.input_directory }}"
    #       exit 1
    #     fi
    #     echo "Using source code from: ${{ inputs.input_directory }}"
    #     ls -la ${{ inputs.input_directory }}
        
    - name: Run codeglide
      uses: madhavi-opsera/aicodegen@v21
      with:
        input_directory: ${{ inputs.input_directory }}
        
