name: Test Secure Action

on:
  workflow_dispatch:
permissions:
  id-token: write       
  contents: read 
jobs:
  test-mcp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: AI Codegenit
        uses: madhavi-opsera/aicodegen@16
          
